---
title: "R Notebook"
output: html_notebook
---

#Toy Car Distance Optimization

## Exploratory Plots + Analysis Plots


```{r}
library(tidyverse)
library(ggpubr)
library(broom)

df <- read.csv("R Data/data.csv")

## Boxplots of Data


distance <- ggplot(data = df, aes(x = "", y = Distance_avg))+
  geom_boxplot()+
  geom_point()+
  labs(y = "Average distance (cm)",
       x = "Response variable")+
  theme_bw()


surface <- ggplot(data = df, aes(x = Surface_type, y = Distance_avg))+
  geom_boxplot()+
  geom_point()+
  labs(y = "Average distance (cm)",
       x = "Surface type")+
  theme_bw()

weight <- ggplot(data = df, aes(x = as.factor(Weight), y = Distance_avg))+
  geom_boxplot()+
  geom_point()+
  labs(y = "Average distance (cm)",
       x = "Additional weight (g)")+
  theme_bw()

angle <- ggplot(data = df, aes(x = as.factor(Angle), y = Distance_avg))+
  geom_boxplot()+
  geom_point()+
  labs(y = "Average distance (cm)",
       x = expression('Angle ('*degree*')'))+
  theme_bw()

ggarrange(distance, surface, weight, angle)

## Dot Plots seperated by surface type

exp3 <- ggplot(df, aes(x=Angle, y= Distance_avg)) +
  geom_point() +
  facet_grid( ~ Surface_type)+
  labs(x = expression('Angle ('*degree*')'), 
       y = "Average distance (cm)")+
  theme_bw()


exp4 <- ggplot(df, aes(x=Weight, y= Distance_avg)) +
  geom_point() +
  facet_grid( ~ Surface_type)+
  labs(x = "Weight (g)", 
       y = "Average distance (cm)")+
  theme_bw()

ggarrange(exp3,exp4, nrow=2, ncol=1)




###### CATEGORICAL MODEL #####

df <- read.csv("R Data/data.csv")

#Convert all x variables to factors
c_var <- c("Surface_type","Weight","Angle") #make all our variables categorical
df[,c_var] <- lapply(df[,c_var],factor)


# Interaction plots

# Angle and weight
inter.angle_weight <- ggplot(data = df, aes(y = Distance_avg))+
  geom_line(aes(x = Angle, 
                color = Weight,
                group = Weight), 
            linewidth = 1)+
  labs(y = "Average distance (cm)")+
  facet_grid(~Surface_type)+
  theme_bw()

# weight and angle
inter.weight_angle <- ggplot(data = df, aes(y = Distance_avg))+
  geom_line(aes(x = Weight, 
                color = Angle,
                group = Angle), 
            linewidth = 1)+
  labs(y = "Average distance (cm)")+
  facet_grid(~Surface_type)+
  theme_bw()

# surface type
inter.surface_type <- ggplot(data = df, aes(y = Distance_avg))+
  geom_line(aes(x = Surface_type, 
                color = Weight,
                group = Weight), 
            linewidth = 1)+
  labs(x = "Surface type",
       y = "Average distance (cm)")+
  facet_grid(~Angle)+
  theme_bw()

ggarrange(inter.weight_angle, inter.angle_weight, inter.surface_type)


## Outlier Plot using IQR Test (coloured)
df_long <- df[, c(5, 6, 7)]

df_long$Treatment <- 1:18

df_long1 <- data.frame(df_long[,1])
colnames(df_long1)[1] = "x"
df_long2 <- data.frame(df_long[,2])
colnames(df_long2)[1] = "x"
df_long3 <- data.frame(df_long[,3])
colnames(df_long3)[1] = "x"

LONG <- rbind(df_long1, df_long2, df_long3)

quart <- quantile(LONG$x)
outliers <- c(quart[2] - (quart[2] * 1.5), quart[3] + (quart[3] * 1.5))
outliers

range(LONG)

# Test for outliers
ggplot(data = df_long)+
  geom_point(aes(x = Treatment, y = Distance_1), color = "blue")+
  geom_point(aes(x = Treatment, y = Distance_2), color = "green")+
  geom_point(aes(x = Treatment, y = Distance_3), color = "red")+
  geom_abline(slope = 0, intercept = outliers[2])+
  theme_bw()


model1_cat <- lm(formula = Distance_avg ~ Surface_type + Angle, data = df)

glance(model1_cat)
summary(model1_cat)

model1_cat_df <- fortify(model1_cat)


# residuals vs each explanatory variable

#resid vs surface_type
resid.surface <- ggplot(data = model1_cat_df, aes(x = Surface_type, y = .resid))+
  geom_point(alpha = 0.5)+
  geom_smooth(se = F)+
  geom_abline(slope = 0, intercept = 0, color = "black", linewidth = 1, linetype = 3)+
  labs(x = "Surface Type",
       y = "Residuals")+
  theme_bw()

#resid vs angle
resid.angle <- ggplot(data = model1_cat_df, aes(x = Angle, y = .resid))+
  geom_point(alpha = 0.5)+
  geom_smooth(se = F)+
  geom_abline(slope = 0, intercept = 0, color = "black", linewidth = 1, linetype = 3)+
  labs(x = expression('Angle ('*degree*')'),
       y = "Residuals")+
  theme_bw()

# residuals vs fitted values
resid.fitted <- ggplot(data = model1_cat_df, aes(x = .fitted, y = .resid))+
  geom_point()+
  geom_smooth(se = F)+
  geom_abline(slope = 0, intercept = 0, color = "black", linewidth = 1, linetype = 3)+
  labs(x = "Fitted Values",
       y = "Residuals")+
  theme_bw()



# histogram of residuals
histo_resid <- ggplot(data = model1_cat_df, aes(x = .resid))+
  geom_histogram(bins = 15)+
  stat_function(fun = dnorm,
                args = list(
                  mean = mean(model1_cat_df$.resid),
                  sd = sd(model1_cat_df$.resid))
                )+
  labs(x = "Residuals")+
  theme_bw()


# indepence plot
independence <- ggplot(data = model1_cat_df, aes(x = seq(1:18), y = .resid))+
  geom_line()+
  geom_smooth(method = lm, se = F)+
  geom_abline(slope = 0, intercept = 0, linetype = 3)+
  labs(x = "Observation number",
       y = "Residuals")+
  theme_bw()


# QQ plot
qq <- ggplot(data = model1_cat_df, aes(sample = .stdresid))+
  stat_qq()+
  geom_abline(intercept = 0,
              slope = 1)+
  labs(x = "Theoretical quantiles",
       y = "Sample quantiles")+
  theme_bw()

ggarrange(resid.surface,resid.angle, 
          resid.fitted, histo_resid, independence, qq)





##### FINAL MODEL #####


df <- read.csv("R Data/data.csv")

#Convert all x variables to factors
c_var <- c("Surface_type","Weight","Angle") #make all our variables categorical
df[,c_var] <- lapply(df[,c_var],factor)

df <- df[, c(1, 2, 3, 4, 8)]

final_model <- lm(formula = log(Distance_avg) ~ Surface_type + Angle + 
                    Surface_type:Angle, data = df)

glance(final_model)
summary(final_model)

final_model_df <- fortify(final_model)


# residuals vs each explanatory variable

#resid vs surface_type
resid.surface <- ggplot(data = final_model_df, aes(x = Surface_type, y = .resid))+
  geom_point(alpha = 0.5)+
  geom_smooth(se = F)+
  geom_abline(slope = 0, intercept = 0, color = "black", linewidth = 1, linetype = 3)+
  labs(x = "Surface Type",
       y = "Residuals")+
  theme_bw()

#resid vs angle
resid.angle <- ggplot(data = final_model_df, aes(x = Angle, y = .resid))+
  geom_point(alpha = 0.5)+
  geom_smooth(se = F)+
  geom_abline(slope = 0, intercept = 0, color = "black", linewidth = 1, linetype = 3)+
  labs(x = expression('Angle ('*degree*')'),
       y = "Residuals")+
  theme_bw()

# residuals vs fitted values
resid.fitted <- ggplot(data = final_model_df, aes(x = .fitted, y = .resid))+
  geom_point()+
  geom_smooth(se = F)+
  geom_abline(slope = 0, intercept = 0, color = "black", linewidth = 1, linetype = 3)+
  labs(x = "Fitted Values",
       y = "Residuals")+
  theme_bw()


# histogram of residuals
histo_resid <- ggplot(data = final_model_df, aes(x = .resid))+
  geom_histogram(bins = 15)+
  stat_function(fun = dnorm,
                args = list(
                  mean = mean(final_model_df$.resid),
                  sd = sd(final_model_df$.resid)))+
  labs(x = "Residuals")+
  theme_bw()


# indepence plot
independence <- ggplot(data = final_model_df, aes(x = seq(1:18), y = .resid))+
  geom_line()+
  geom_smooth(method = lm, se = F)+
  geom_abline(slope = 0, intercept = 0, linetype = 3)+
  labs(x = "Observation number",
       y = "Residuals")+
  theme_bw()


# QQ plot
qq <- ggplot(data = final_model_df, aes(sample = .stdresid))+
  stat_qq()+
  geom_abline(intercept = 0,
              slope = 1)+
  labs(x = "Theoretical quantiles",
       y = "Sample quantiles")+
  theme_bw()

ggarrange(resid.surface,resid.angle,
          resid.fitted, histo_resid, independence, qq)



##### ANOVA on final model #####



fit.anova <- aov(lm(formula = log(Distance_avg) ~ Surface_type + Angle + 
                         Surface_type:Angle, data = df))

summary(fit.anova)

# Tukey's HSD
tukeys_HSD <- TukeyHSD(fit.anova)

par(mar = c(5,10,4,5))
plot(TukeyHSD(fit.anova, conf.level=.95), las = 2)


# Plot final model

# Does surface type have an effect?
surface_type_plot <- ggplot(data = final_model_df, 
                            aes(x = Surface_type, 
                            y = .fitted,
                            color = Angle,
                            group = Angle))+
  geom_point()+
  geom_line()+
  geom_errorbar(aes(ymin = .fitted - (.sigma / 2),
                    ymax = .fitted + (.sigma / 2)))+
  labs(x = "Surface type",
       y = "Fitted values")+
  theme_bw()

# Does Angle have an effect
angle_plot <- ggplot(data = final_model_df, 
                     aes(x = Angle, 
                         y = .fitted,
                         color = Surface_type,
                         group = Surface_type))+
  geom_point()+
  geom_line()+
  geom_errorbar(aes(ymin = .fitted - (.sigma / 2),
                    ymax = .fitted + (.sigma / 2)))+
  labs(x = expression('Angle ('*degree*')'),
       y = "Fitted values",
       color = "Surface type")+
  theme_bw()


ggarrange(surface_type_plot, angle_plot)

```

_
## Premable + Data Read

```{r, include=TRUE, warning=FALSE, message=FALSE, error=FALSE}

# refresh R, install + library required packages.
source("./scripts/setup.r") 

# Read in data
df <- read.csv(here("data","data.csv"))

# Make all our variables categorical factors
c_var <- c("Surface_type","Weight","Angle") 
df[,c_var] <- lapply(df[,c_var],factor)
```

## Outliers

```{r}
## Setup Outlier Dataframew
df_long <- df[, c(5, 6, 7)]

df_long1 <- data.frame(df_long[,1])
colnames(df_long1)[1] = "x"
df_long2 <- data.frame(df_long[,2])
colnames(df_long2)[1] = "x"
df_long3 <- data.frame(df_long[,3])
colnames(df_long3)[1] = "x"

LONG <- rbind(df_long1, df_long2, df_long3)

quart <- quantile(LONG$x)
outliers <- c(quart[2] - (quart[2] * 1.5), quart[3] + (quart[3] * 1.5))
outliers

range(LONG)

# Test for outliers (not-coloured)
ggplot(data = df) +
  geom_point(aes(x = Treatment, y = Distance_1), color = "black")+
  geom_point(aes(x = Treatment, y = Distance_2), color = "black")+
  geom_point(aes(x = Treatment, y = Distance_3), color = "black")+
  geom_abline(slope = 0, intercept = outliers[2])+
  theme_bw()+
  ylab("Distance (cm)")+
  xlab("Index")
```

## Model Selection 1 (Initial)

```{r}
# Remove Unnecessary Columns we can add them back later
df <- df[,-1]
df <- df[,-4:-6]


# Create Empty and Full Models for stepwise regression

m.empty <- lm(Distance_avg ~ 1,
              data = df)

m.full.1w <- lm(Distance_avg ~., 
              data = df)

m.full.2w <- lm(Distance_avg ~.^2, 
              data = df)

# Conduct Stepwise Regression


m.step.1w.f <- step(m.empty,
                direction = "forward")

m.step.1w.r <- step(m.full.1w,
                direction = "backward")

m.step.1w.b <- step(m.full.1w,
                direction = "both")

m.step.2w.b <- step(m.full.2w,
                direction = "both")

# Create a model list

model.list <- list(
  "Forward-One-Way" = m.step.1w.f,
  "Backward-One-Way" = m.step.1w.r,
  "Both-One-Way" = m.step.1w.b,
  "Both-Two-Way" = m.step.2w.b)

# Apply BIC to stepwise models

bics <- sapply(model.list,FUN = BIC)

# Tabulate BIC Results

plot_data <- data.frame(
                  model = c("Forward-One-Way",
                            "Backward-One-Way",
                            "Both-One-Way", 
                            "Both-Two-Way"),
                  Bic = bics)

knitr::kable(plot_data,row.names = FALSE,
             col.names = c("Model","BIC"))

```

## Model Evaluation 1 (Initial)

```{r}
## Obtain Model Summary
summary(m.step.1w.b)

# Check Linear Regression Assumptions
par(mfrow = c(2,2))
plot(m.step.1w.b$fitted.values,m.step.1w.b$residuals)
abline(h=0,col='red')
plot(m.step.1w.b$residuals,type = "l")
abline(h=0,col='red')
hist(m.step.1w.b$residuals)
qqnorm(m.step.1w.b$residuals)
qqline(m.step.1w.b$residuals)

```

## Model Selection 2 (log-transform)

```{r}
# Create Empty and Full models for stepwise (using log transformed response)

m.empty.log <- lm(log(Distance_avg) ~ 1,
              data = df)

m.full.1w.log <- lm(log(Distance_avg) ~., 
              data = df)

m.full.2w.log <- lm(log(Distance_avg) ~.^2, 
              data = df)


## conduct Stepwise Regression

m.step.1w.f.log <- step(m.empty.log,
                direction = "forward")

m.step.1w.r.log <- step(m.full.1w.log,
                direction = "backward")

m.step.1w.b.log <- step(m.full.1w.log,
                direction = "both")

m.step.2w.b.log <- step(m.full.2w.log,
                direction = "both")

# Create a Model List for Log Models

model.list <- list(
  "Forward-One-Way (Log)" = m.step.1w.f.log,
  "Backward-One-Way (Log)" = m.step.1w.r.log,
  "Both-One-Way (Log)" = m.step.1w.b.log,
  "Both-Two-Way (Log)" = m.step.2w.b.log)

# Apply BIC to all log stepwise models

bics.log <- sapply(model.list,FUN = BIC)

#Tabulate Results for log models
plot_data <- data.frame(
                  model = c("Forward-One-Way (Log)",
                            "Backward-One-Way (Log)",
                            "Both-One-Way (Log)", 
                            "Both-Two-Way (Log)"),
                  Bic = bics.log)

knitr::kable(plot_data,row.names = FALSE,
             col.names = c("Model","BIC"))

```

We can create a nested model without weight and use an partial-f test to compare with hypotheses:

- H0: $b_w=0$
- H1: $b_w\ne0$

```{r}
## Make the nested model with weight removed
nested.log <- lm(formula = log(Distance_avg) ~ Surface_type + Angle +
    Surface_type:Angle, data = df)

# Test With Partial F test
anova(nested.log,m.step.2w.b.log)
```


## Model Stastics 

```{r}
# Create Glances for all models
x <- glance(m.step.1w.b)
y <- glance(m.step.2w.b.log)
z <- glance(nested.log)
models <- c("Inital: Step One Way", "Intermediate: Step Two Way (log)", "Final : Nested (log)")

# Join them in a data frame
rdf <- data.frame(rbind(x,y,z))

# add model name column
cbind(models = models,rdf)

```


## Analysis of Variance

```{r}
# Create an Anova for the full model
fit.anova <- aov(nested.log, data = df)


# Create a summary of the ANOVA
summary(fit.anova)

# Perform Tukey's

thsd_aov <- TukeyHSD(fit.anova)
thsd_aov



```




